from __future__ import annotations

import shutil
from dataclasses import asdict, dataclass
from pathlib import Path

from .util import atomic_write_text, run_command

CONFIGURE_TEMPLATE = r'''#!/usr/bin/env python3
"""Assembly-only N64 matching build helper generated by n64recomp-kit."""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent
BUILD_DIR = ROOT / "build"
ASM_DIR = ROOT / "asm"
BASEROM = ROOT / "baserom.z64"
TARGET_ELF = BUILD_DIR / "__GAME_SLUG__.elf"
TARGET_ROM = BUILD_DIR / "__GAME_SLUG__.z64"
LD_SCRIPT = ROOT / "__GAME_SLUG__.ld"
AS = os.environ.get("AS", "mips-linux-gnu-as")
LD = os.environ.get("LD", "mips-linux-gnu-ld")
OBJCOPY = os.environ.get("OBJCOPY", "mips-linux-gnu-objcopy")
ASFLAGS = os.environ.get("ASFLAGS", "-EB -mips3" + (" -I include" if (ROOT / "include" / "macro.inc").is_file() else ""))
LDFLAGS = os.environ.get("LDFLAGS", f"-nostdlib -T {LD_SCRIPT}")
OBJCOPYFLAGS = os.environ.get("OBJCOPYFLAGS", "-O binary --gap-fill 0x00")


def asm_sources() -> list[Path]:
    return sorted([*ASM_DIR.rglob("*.s"), *ASM_DIR.rglob("*.S")])


def run(command: list[str]) -> None:
    print("[run]", " ".join(command))
    subprocess.check_call(command, cwd=str(ROOT))


def safe_clean_build() -> None:
    target = BUILD_DIR.resolve()
    if target == ROOT or target == Path.home().resolve() or len(target.parts) <= 2:
        raise SystemExit(f"Refusing to remove unsafe build path: {target}")
    shutil.rmtree(target)


def configure(clean: bool) -> None:
    if clean and BUILD_DIR.exists():
        safe_clean_build()
    if not ASM_DIR.is_dir():
        raise SystemExit(f"Missing assembly directory: {ASM_DIR}")
    if not LD_SCRIPT.is_file():
        raise SystemExit(f"Missing linker script: {LD_SCRIPT}")
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    sources = asm_sources()
    if not sources:
        raise SystemExit("No .s or .S files were found under asm; run Splat split first.")

    import re
    ld_content = LD_SCRIPT.read_text(encoding="utf-8")
    asset_refs: list[tuple[Path, Path]] = []
    ASSETS_DIR = ROOT / "assets"
    for m in re.finditer(r"build/assets/([^/\s\)]+)\.o", ld_content):
        asset_name = m.group(1)
        bin_src = ASSETS_DIR / f"{asset_name}.bin"
        obj_dest = BUILD_DIR / "assets" / f"{asset_name}.o"
        if bin_src.is_file():
            asset_refs.append((bin_src, obj_dest))
            obj_dest.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "ninja_required_version = 1.10",
        "builddir = build",
        "",
        "rule asm",
        "  command = $as $asflags -o $out $in",
        "",
        "rule binobj",
        "  command = $objcopy -I binary -O elf32-tradbigmips -B mips:4000 $in $out",
        "",
        "rule link",
        "  command = $ld $ldflags -o $out $in",
        "",
        "rule binary",
        "  command = $objcopy $objcopyflags $in $out",
        "",
    ]
    objects: list[str] = []
    for src in sources:
        rel = src.relative_to(ROOT)
        obj = BUILD_DIR / rel.with_suffix(".o")
        obj.parent.mkdir(parents=True, exist_ok=True)
        objects.append(str(obj.relative_to(ROOT)))
        lines.extend([
            f"build {obj.relative_to(ROOT)}: asm {rel}",
            f"  as = {AS}",
            f"  asflags = {ASFLAGS}",
            "",
        ])
    for bin_src, obj_dest in asset_refs:
        objects.append(str(obj_dest.relative_to(ROOT)))
        lines.extend([
            f"build {obj_dest.relative_to(ROOT)}: binobj {bin_src.relative_to(ROOT)}",
            f"  objcopy = {OBJCOPY}",
            "",
        ])
    if asset_refs:
        print(f"Added {len(asset_refs)} binary asset object(s).")
    lines.extend([
        f"build {TARGET_ELF.relative_to(ROOT)}: link {' '.join(objects)}",
        f"  ld = {LD}",
        f"  ldflags = {LDFLAGS}",
        "",
        f"build {TARGET_ROM.relative_to(ROOT)}: binary {TARGET_ELF.relative_to(ROOT)}",
        f"  objcopy = {OBJCOPY}",
        f"  objcopyflags = {OBJCOPYFLAGS}",
        "",
        f"default {TARGET_ROM.relative_to(ROOT)}",
        "",
    ])
    temp = ROOT / ".build.ninja.tmp"
    temp.write_text("\n".join(lines), encoding="utf-8")
    os.replace(temp, ROOT / "build.ninja")
    print(f"Configured {len(objects)} assembly object(s).")


def build() -> None:
    run(["ninja", "-f", "build.ninja"])


def first_mismatch(left: bytes, right: bytes) -> int | None:
    limit = min(len(left), len(right))
    for index in range(limit):
        if left[index] != right[index]:
            return index
    return limit if len(left) != len(right) else None


def diff() -> None:
    if not BASEROM.is_file():
        raise SystemExit(f"Missing {BASEROM}")
    if not TARGET_ROM.is_file():
        raise SystemExit(f"Missing {TARGET_ROM}; run --build first.")
    expected = BASEROM.read_bytes()
    actual = TARGET_ROM.read_bytes()
    mismatch = first_mismatch(expected, actual)
    if mismatch is None:
        print("ROMs match byte-for-byte.")
        return
    expected_byte = expected[mismatch] if mismatch < len(expected) else None
    actual_byte = actual[mismatch] if mismatch < len(actual) else None
    print(f"ROM mismatch at 0x{mismatch:X}: expected={expected_byte!r} actual={actual_byte!r}")
    print(f"Sizes: expected={len(expected)} actual={len(actual)}")
    raise SystemExit(1)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--clean", action="store_true")
    parser.add_argument("--build", action="store_true")
    parser.add_argument("--diff", action="store_true")
    args = parser.parse_args()
    configure(args.clean)
    if args.build:
        build()
    if args.diff:
        diff()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


@dataclass
class MatchingConfigureReport:
    path: str
    game: str
    asm_dir: str
    linker_script: str
    wrote: bool

    def to_dict(self) -> dict:
        return asdict(self)


def emit_matching_configure(root_path: str | Path = ".", *, game: str, overwrite: bool = False) -> MatchingConfigureReport:
    root = Path(root_path).resolve()
    root.mkdir(parents=True, exist_ok=True)
    if not game or any(ch in game for ch in " /\\:\t\n\r"):
        raise ValueError("game must be a non-empty slug without spaces, slashes, or colons")
    out = root / "configure.py"
    if out.exists() and not overwrite:
        raise FileExistsError(f"configure.py already exists: {out}")
    text = CONFIGURE_TEMPLATE.replace("__GAME_SLUG__", game)
    atomic_write_text(out, text)
    try:
        out.chmod(out.stat().st_mode | 0o111)
    except OSError:
        pass
    return MatchingConfigureReport(
        path=str(out),
        game=game,
        asm_dir=str(root / "asm"),
        linker_script=str(root / f"{game}.ld"),
        wrote=True,
    )


def run_configure_min(root_path: str | Path = ".", *, clean: bool = False, build: bool = False, diff: bool = False, timeout: int | None = None) -> dict:
    root = Path(root_path).resolve()
    script = root / "configure.py"
    if not script.is_file():
        raise FileNotFoundError(f"configure.py not found: {script}")
    python = shutil.which("python") or shutil.which("python3")
    if not python:
        raise FileNotFoundError("python executable not found on PATH")
    command = [python, script.name]
    if clean:
        command.append("--clean")
    if build:
        command.append("--build")
    if diff:
        command.append("--diff")
    result = run_command(command, cwd=root, timeout=timeout)
    return {
        "ok": result.returncode == 0,
        "command": result.command,
        "returncode": result.returncode,
        "stdout": result.stdout,
        "stderr": result.stderr,
        "seconds": result.seconds,
    }
